version: 2
jobs:
  execute:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn install
      - run: node sample.js
workflows:
  version: 2
  execute-workflow:
    triggers:
      - schedule:
          cron: '46 * * * *'
          filters:
            branches:
              only:
                - master
    jobs:
      - execute
